// Filter options based on Swooped.co job search interface

export const EXPERIENCE_LEVEL_OPTIONS = [
  { value: "all", label: "All" },
  { value: "internship", label: "Internship" },
  { value: "entry_level", label: "Entry Level" },
  { value: "associate", label: "Associate" },
  { value: "mid_senior", label: "Mid Senior" },
  { value: "director", label: "Director" },
  { value: "executive", label: "Executive" },
] as const;

export const JOB_FUNCTION_OPTIONS = [
  { value: "all", label: "All" },
  { value: "accounting", label: "Accounting" },
  { value: "administrative", label: "Administrative" },
  { value: "arts_design", label: "Arts and Design" },
  { value: "business_development", label: "Business Development" },
  { value: "community_social", label: "Community and Social Services" },
  { value: "consulting", label: "Consulting" },
  { value: "customer_service", label: "Customer Service" },
  { value: "education", label: "Education" },
  { value: "engineering", label: "Engineering" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "finance", label: "Finance" },
  { value: "healthcare", label: "Healthcare Services" },
  { value: "human_resources", label: "Human Resources" },
  { value: "information_technology", label: "Information Technology" },
  { value: "legal", label: "Legal" },
  { value: "marketing", label: "Marketing" },
  { value: "media_communications", label: "Media and Communications" },
  { value: "military_protective", label: "Military and Protective Services" },
  { value: "operations", label: "Operations" },
  { value: "product_management", label: "Product Management" },
  { value: "program_project_management", label: "Program and Project Management" },
  { value: "purchasing", label: "Purchasing" },
  { value: "quality_assurance", label: "Quality Assurance" },
  { value: "real_estate", label: "Real Estate" },
  { value: "research", label: "Research" },
  { value: "sales", label: "Sales" },
  { value: "support", label: "Support" },
] as const;

export const INDUSTRY_OPTIONS = [
  { value: "all", label: "All" },
  { value: "accounting", label: "Accounting" },
  { value: "airlines_aviation", label: "Airlines/Aviation" },
  { value: "alternative_dispute_resolution", label: "Alternative Dispute Resolution" },
  { value: "alternative_medicine", label: "Alternative Medicine" },
  { value: "animation", label: "Animation" },
  { value: "apparel_fashion", label: "Apparel & Fashion" },
  { value: "architecture_planning", label: "Architecture & Planning" },
  { value: "arts_crafts", label: "Arts and Crafts" },
  { value: "automotive", label: "Automotive" },
  { value: "aviation_aerospace", label: "Aviation & Aerospace" },
  { value: "banking", label: "Banking" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "broadcast_media", label: "Broadcast Media" },
  { value: "building_materials", label: "Building Materials" },
  { value: "business_supplies_equipment", label: "Business Supplies and Equipment" },
  { value: "capital_markets", label: "Capital Markets" },
  { value: "chemicals", label: "Chemicals" },
  { value: "civic_social_organization", label: "Civic & Social Organization" },
  { value: "civil_engineering", label: "Civil Engineering" },
  { value: "commercial_real_estate", label: "Commercial Real Estate" },
  { value: "computer_network_security", label: "Computer & Network Security" },
  { value: "computer_games", label: "Computer Games" },
  { value: "computer_hardware", label: "Computer Hardware" },
  { value: "computer_networking", label: "Computer Networking" },
  { value: "computer_software", label: "Computer Software" },
  { value: "construction", label: "Construction" },
  { value: "consumer_electronics", label: "Consumer Electronics" },
  { value: "consumer_goods", label: "Consumer Goods" },
  { value: "consumer_services", label: "Consumer Services" },
  { value: "cosmetics", label: "Cosmetics" },
  { value: "dairy", label: "Dairy" },
  { value: "defense_space", label: "Defense & Space" },
  { value: "design", label: "Design" },
  { value: "e_learning", label: "E-Learning" },
  { value: "education_management", label: "Education Management" },
  { value: "electrical_electronic_manufacturing", label: "Electrical/Electronic Manufacturing" },
  { value: "entertainment", label: "Entertainment" },
  { value: "environmental_services", label: "Environmental Services" },
  { value: "events_services", label: "Events Services" },
  { value: "executive_office", label: "Executive Office" },
  { value: "facilities_services", label: "Facilities Services" },
  { value: "farming", label: "Farming" },
  { value: "financial_services", label: "Financial Services" },
  { value: "fine_art", label: "Fine Art" },
  { value: "fishery", label: "Fishery" },
  { value: "food_beverages", label: "Food & Beverages" },
  { value: "food_production", label: "Food Production" },
  { value: "fundraising", label: "Fundraising" },
  { value: "furniture", label: "Furniture" },
  { value: "gambling_casinos", label: "Gambling & Casinos" },
  { value: "glass_ceramics_concrete", label: "Glass, Ceramics & Concrete" },
  { value: "government_administration", label: "Government Administration" },
  { value: "government_relations", label: "Government Relations" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "health_wellness_fitness", label: "Health, Wellness and Fitness" },
  { value: "higher_education", label: "Higher Education" },
  { value: "hospital_health_care", label: "Hospital & Health Care" },
  { value: "hospitality", label: "Hospitality" },
  { value: "human_resources", label: "Human Resources" },
  { value: "import_export", label: "Import and Export" },
  { value: "individual_family_services", label: "Individual & Family Services" },
  { value: "industrial_automation", label: "Industrial Automation" },
  { value: "information_services", label: "Information Services" },
  { value: "information_technology", label: "Information Technology and Services" },
  { value: "insurance", label: "Insurance" },
  { value: "international_affairs", label: "International Affairs" },
  { value: "international_trade_development", label: "International Trade and Development" },
  { value: "internet", label: "Internet" },
  { value: "investment_banking", label: "Investment Banking" },
  { value: "investment_management", label: "Investment Management" },
  { value: "judiciary", label: "Judiciary" },
  { value: "law_enforcement", label: "Law Enforcement" },
  { value: "law_practice", label: "Law Practice" },
  { value: "legal_services", label: "Legal Services" },
  { value: "legislative_office", label: "Legislative Office" },
  { value: "leisure_travel_tourism", label: "Leisure, Travel & Tourism" },
  { value: "libraries", label: "Libraries" },
  { value: "logistics_supply_chain", label: "Logistics and Supply Chain" },
  { value: "luxury_goods_jewelry", label: "Luxury Goods & Jewelry" },
  { value: "machinery", label: "Machinery" },
  { value: "management_consulting", label: "Management Consulting" },
  { value: "maritime", label: "Maritime" },
  { value: "market_research", label: "Market Research" },
  { value: "marketing_advertising", label: "Marketing and Advertising" },
  { value: "mechanical_industrial_engineering", label: "Mechanical or Industrial Engineering" },
  { value: "media_production", label: "Media Production" },
  { value: "medical_devices", label: "Medical Devices" },
  { value: "medical_practice", label: "Medical Practice" },
  { value: "mental_health_care", label: "Mental Health Care" },
  { value: "military", label: "Military" },
  { value: "mining_metals", label: "Mining & Metals" },
  { value: "motion_pictures_film", label: "Motion Pictures and Film" },
  { value: "museums_institutions", label: "Museums and Institutions" },
  { value: "music", label: "Music" },
  { value: "nanotechnology", label: "Nanotechnology" },
  { value: "newspapers", label: "Newspapers" },
  { value: "nonprofit_organization_management", label: "Nonprofit Organization Management" },
  { value: "oil_energy", label: "Oil & Energy" },
  { value: "online_media", label: "Online Media" },
  { value: "outsourcing_offshoring", label: "Outsourcing/Offshoring" },
  { value: "package_freight_delivery", label: "Package/Freight Delivery" },
  { value: "packaging_containers", label: "Packaging and Containers" },
  { value: "paper_forest_products", label: "Paper & Forest Products" },
  { value: "performing_arts", label: "Performing Arts" },
  { value: "pharmaceuticals", label: "Pharmaceuticals" },
  { value: "philanthropy", label: "Philanthropy" },
  { value: "photography", label: "Photography" },
  { value: "plastics", label: "Plastics" },
  { value: "political_organization", label: "Political Organization" },
  { value: "primary_secondary_education", label: "Primary/Secondary Education" },
  { value: "printing", label: "Printing" },
  { value: "professional_training_coaching", label: "Professional Training & Coaching" },
  { value: "program_development", label: "Program Development" },
  { value: "public_policy", label: "Public Policy" },
  { value: "public_relations_communications", label: "Public Relations and Communications" },
  { value: "public_safety", label: "Public Safety" },
  { value: "publishing", label: "Publishing" },
  { value: "railroad_manufacture", label: "Railroad Manufacture" },
  { value: "ranching", label: "Ranching" },
  { value: "real_estate", label: "Real Estate" },
  { value: "recreational_facilities_services", label: "Recreational Facilities and Services" },
  { value: "religious_institutions", label: "Religious Institutions" },
  { value: "renewables_environment", label: "Renewables & Environment" },
  { value: "research", label: "Research" },
  { value: "restaurants", label: "Restaurants" },
  { value: "retail", label: "Retail" },
  { value: "security_investigations", label: "Security and Investigations" },
  { value: "semiconductors", label: "Semiconductors" },
  { value: "shipbuilding", label: "Shipbuilding" },
  { value: "sporting_goods", label: "Sporting Goods" },
  { value: "sports", label: "Sports" },
  { value: "staffing_recruiting", label: "Staffing and Recruiting" },
  { value: "supermarkets", label: "Supermarkets" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "textiles", label: "Textiles" },
  { value: "think_tanks", label: "Think Tanks" },
  { value: "tobacco", label: "Tobacco" },
  { value: "translation_localization", label: "Translation and Localization" },
  { value: "transportation_trucking_railroad", label: "Transportation/Trucking/Railroad" },
  { value: "utilities", label: "Utilities" },
  { value: "venture_capital_private_equity", label: "Venture Capital & Private Equity" },
  { value: "veterinary", label: "Veterinary" },
  { value: "warehousing", label: "Warehousing" },
  { value: "wholesale", label: "Wholesale" },
  { value: "wine_spirits", label: "Wine and Spirits" },
  { value: "wireless", label: "Wireless" },
  { value: "writing_editing", label: "Writing and Editing" },
] as const;

export const LOCATION_DISTANCE_OPTIONS = [
  { value: "25", label: "25 miles" },
  { value: "50", label: "50 miles" },
  { value: "100", label: "100 miles" },
  { value: "anywhere", label: "Anywhere" },
] as const;

export const OFFICE_REQUIREMENTS_OPTIONS = [
  { value: "all", label: "All" },
  { value: "on-site", label: "On-site" },
  { value: "hybrid", label: "Hybrid" },
  { value: "remote", label: "Remote" },
] as const;

export const DATE_POSTED_OPTIONS = [
  { value: "all", label: "Anytime" },
  { value: "today", label: "Past 24 hours" },
  { value: "3days", label: "Past 3 days" },
  { value: "week", label: "Past week" },
  { value: "month", label: "Past month" },
] as const;

export const EMPLOYMENT_TYPE_OPTIONS = [
  { value: "all", label: "All" },
  { value: "fulltime", label: "Full-time" },
  { value: "parttime", label: "Part-time" },
  { value: "contract", label: "Contract" },
  { value: "internship", label: "Internship" },
  { value: "temporary", label: "Temporary" },
] as const;

// Type exports for filter values
export type ExperienceLevel = typeof EXPERIENCE_LEVEL_OPTIONS[number]["value"];
export type JobFunction = typeof JOB_FUNCTION_OPTIONS[number]["value"];
export type Industry = typeof INDUSTRY_OPTIONS[number]["value"];
export type LocationDistance = typeof LOCATION_DISTANCE_OPTIONS[number]["value"];
export type OfficeRequirement = typeof OFFICE_REQUIREMENTS_OPTIONS[number]["value"];
export type DatePosted = typeof DATE_POSTED_OPTIONS[number]["value"];
export type EmploymentType = typeof EMPLOYMENT_TYPE_OPTIONS[number]["value"];
